Fix compilation for Rust module
Summary:
There must have been a change to `libc::iovec` and `libc::sockaddr_in6` as neither implements `fmt::Debug` now:

```
$ cargo build
   Compiling netconsd_module v0.1.0 (/data/users/matwood/fbsource/fbcode/kernel/netcons/netconsd/rust/module)
warning: hard linking files in the incremental compilation cache failed. copying files instead. consider moving the cache directory to a file system which supports hard linking in session dir `/data/users/matwood/fbsource/fbcode/kernel/netcons/netconsd/rust/module/target/debug/incremental/netconsd_module-ru80e0qm60xh/s-gt9ng2y7vx-1kczabb-working`

error[E0277]: `iovec` doesn't implement `Debug`
  --> src/lib.rs:26:5
   |
23 | #[derive(Debug)]
   |          ----- in this derive macro expansion
...
26 |     pub iovec: iovec,                                                                                                                                                                                                                                        ────
   |     ^^^^^^^^^^^^^^^^ `iovec` cannot be formatted using `{:?}` because it doesn't implement `Debug`                                                                                                                                                           KKSU
   |
   = help: the trait `Debug` is not implemented for `iovec`                                                                                                                                                                                                       UUMS
   = note: this error originates in the derive macro `Debug` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: `sockaddr_in6` doesn't implement `Debug`
  --> src/lib.rs:27:5
   |
23 | #[derive(Debug)]
   |          ----- in this derive macro expansion
...
27 |     pub src: sockaddr_in6,
   |     ^^^^^^^^^^^^^^^^^^^^^ `sockaddr_in6` cannot be formatted using `{:?}` because it doesn't implement `Debug`
   |
   = help: the trait `Debug` is not implemented for `sockaddr_in6`
   = note: this error originates in the derive macro `Debug` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
warning: `netconsd_module` (lib) generated 1 warning                                                                                                                                                                                                              00 0
error: could not compile `netconsd_module` (lib) due to 2 previous errors; 1 warning emitted
```

 ---

This diff replaces `#[derive(Debug)]` on `MsgBuf` with a custom `fmt::Debug` impl that only uses the fields we can show debug info for.

Reviewed By: kernelslacker

Differential Revision: D53633790

fbshipit-source-id: da959ebc401c6710d2471bcfdedecba39729458f