logger: add missing include
Summary:
Found this while attempting to package netconsd in Fedora

```
g++ logger.cc -std=c++11 -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fno-strict-aliasing -Wall -Wextra -Wmissing-declarations -Wno-missing-field-initializers -Wno-unused-parameter -fPIC -I../ncrx -I../include -shared -static-libstdc++ -static-libgcc -c -o logger.o
make[1]: Leaving directory '/builddir/build/BUILD/netconsd-12e6a2fb507a95c59931eda3e04c2134f91e1d71/modules'
logger.cc: In constructor 'logtarget::logtarget(in6_addr*)':
logger.cc:79:84: error: 'errno' was not declared in this scope
   79 |                                 fprintf(stderr, "inet_ntop failed: %s\n", strerror(errno));
      |                                                                                    ^~~~~
logger.cc:29:1: note: 'errno' is defined in header '<cerrno>'; did you forget to '#include <cerrno>'?
   28 | #include <jhash.h>
  +++ |+#include <cerrno>
   29 |
make[1]: *** [Makefile:21: logger.so] Error 1
make: *** [Makefile:49: mods] Error 2
```

Reviewed By: kernelslacker

Differential Revision: D31544292

fbshipit-source-id: 30057a4c7f90af380bd2401419aac3182f998a74