Fix omission of CFLAGS from link invocation of CC in Makefile
On Debian, the current Makefile fails to generate "debug" builds:

	cc -lasan -lubsan ncrx/libncrx.o threads.o listener.o worker.o output.o main.o -lpthread -lrt -ldl -o netconsd
	<snip>
	/home/calvinow/git/netconsd/main.c:166: undefined reference to `__asan_init'
	/usr/bin/ld: /home/calvinow/git/netconsd/main.c:166: undefined reference to `__asan_version_mismatch_check_v8'
	/usr/bin/ld: /home/calvinow/git/netconsd/main.c:166: undefined reference to `__asan_register_globals'
	collect2: error: ld returned 1 exit status
	make: *** [Makefile:36: netconsd] Error 1

This happens because I omitted "-fsanitize=blah" from the final CC
invocation. Easy to fix.